import type { SpiritualTopic, Verse } from "../types";
import { getLocalCuvPool } from "./seed";
import { hashDateSeed } from "../hash";
import { getTodayKey } from "../scheduler";
import { attachEnglish } from "./bilingual";

/** 显示名（和合本用语优先） */
export const TOPIC_LABELS: Record<SpiritualTopic, string> = {
  hope: "盼望",
  comfort: "安慰",
  faith: "信心",
  strength: "刚强",
  wisdom: "智慧",
  gratitude: "感恩",
  presence: "同在",
  salvation: "救恩",
  // 圣灵九果
  love: "仁爱",
  joy: "喜乐",
  peace: "和平",
  patience: "忍耐",
  kindness: "恩慈",
  goodness: "良善",
  faithfulness: "信实",
  gentleness: "温柔",
  self_control: "节制",
};

/** 一般生命主题（不含九果，避免 chips 重复） */
export const LIFE_TOPICS: SpiritualTopic[] = [
  "hope",
  "comfort",
  "faith",
  "strength",
  "wisdom",
  "gratitude",
  "presence",
  "salvation",
];

/**
 * 圣灵所结的果子（加拉太书 5:22-23）
 * 仁爱、喜乐、和平、忍耐、恩慈、良善、信实、温柔、节制
 */
export const FRUIT_TOPICS: SpiritualTopic[] = [
  "love",
  "joy",
  "peace",
  "patience",
  "kindness",
  "goodness",
  "faithfulness",
  "gentleness",
  "self_control",
];

export const ALL_TOPICS = [
  ...LIFE_TOPICS,
  ...FRUIT_TOPICS,
] as SpiritualTopic[];

export const FRUIT_VERSE_REF = "加拉太书 5:22-23";

export const FRUIT_INTRO =
  "圣灵所结的果子，就是仁爱、喜乐、和平、忍耐、恩慈、良善、信实、温柔、节制。";

/** 按经文引用挂主题 */
const TOPIC_BY_REFERENCE: Record<string, SpiritualTopic[]> = {
  "约翰福音 3:16": ["love", "salvation", "hope"],
  "诗篇 23:1": ["presence", "comfort", "peace"],
  "箴言 3:5-6": ["faith", "wisdom", "faithfulness"],
  "以赛亚书 40:31": ["hope", "strength", "patience"],
  "耶利米书 29:11": ["hope", "peace"],
  "马太福音 11:28": ["comfort", "peace", "gentleness"],
  "约翰福音 14:27": ["peace", "comfort"],
  "罗马书 8:28": ["hope", "faith", "goodness"],
  "腓立比书 4:6-7": ["peace", "gratitude", "joy"],
  "腓立比书 4:13": ["strength", "faith"],
  "诗篇 46:10": ["peace", "presence", "self_control"],
  "诗篇 119:105": ["wisdom", "presence"],
  "约书亚记 1:9": ["strength", "presence"],
  "哥林多后书 12:9": ["strength", "comfort", "gentleness"],
  "希伯来书 11:1": ["faith", "hope", "faithfulness"],
  "加拉太书 5:22-23": [
    "love",
    "joy",
    "peace",
    "patience",
    "kindness",
    "goodness",
    "faithfulness",
    "gentleness",
    "self_control",
  ],
  "弥迦书 6:8": ["wisdom", "love", "kindness", "gentleness"],
  "马太福音 5:14-16": ["presence", "love", "goodness"],
  "约翰一书 4:19": ["love"],
  "诗篇 27:1": ["strength", "presence", "peace"],
  "以赛亚书 41:10": ["strength", "comfort", "presence"],
  "马太福音 6:33": ["faith", "wisdom", "self_control"],
  "罗马书 12:2": ["wisdom", "faith", "self_control"],
  "歌罗西书 3:15": ["peace", "gratitude", "gentleness"],
  "彼得前书 5:7": ["comfort", "peace"],
  "雅各书 1:17": ["gratitude", "love", "goodness"],
  "诗篇 34:8": ["gratitude", "presence", "goodness"],
  "耶利米哀歌 3:22-23": ["hope", "love", "gratitude", "faithfulness"],
  "提摩太后书 1:7": ["strength", "love", "peace", "self_control"],
  "启示录 21:4": ["hope", "comfort", "salvation"],
  "创世记 1:1": ["presence", "wisdom"],
  "诗篇 91:1-2": ["presence", "strength", "peace"],
  "以赛亚书 26:3": ["peace", "faith"],
  "约翰福音 8:12": ["presence", "salvation", "joy"],
  "罗马书 15:13": ["hope", "peace", "joy"],
  "以弗所书 2:8-9": ["salvation", "faith"],
  "诗篇 37:5": ["faith", "hope", "faithfulness"],
  "申命记 31:6": ["strength", "presence"],
  "哥林多前书 13:13": ["love", "faith", "hope"],
  "诗篇 139:14": ["gratitude", "love", "joy"],
  "那鸿书 1:7": ["comfort", "presence", "goodness"],
  "约翰福音 15:5": ["presence", "faith", "faithfulness"],
  "诗篇 62:5-6": ["hope", "peace", "faith", "patience"],
  "马太福音 28:20": ["presence", "hope"],
  // 九果补充经文
  "尼希米记 8:10": ["joy", "strength"],
  "诗篇 16:11": ["joy", "presence"],
  "约翰福音 15:11": ["joy", "love"],
  "雅各书 1:2-3": ["joy", "patience", "faith"],
  "罗马书 12:12": ["joy", "hope", "patience"],
  "歌罗西书 1:11": ["patience", "strength", "joy"],
  "以弗所书 4:2": ["patience", "gentleness", "love"],
  "雅各书 5:7-8": ["patience", "hope"],
  "以弗所书 4:32": ["kindness", "love", "gentleness"],
  "歌罗西书 3:12": ["kindness", "gentleness", "patience", "love"],
  "箴言 11:17": ["kindness", "goodness"],
  "诗篇 23:6": ["goodness", "presence", "love"],
  "罗马书 12:9": ["goodness", "love"],
  "诗篇 100:5": ["faithfulness", "love", "gratitude"],
  "耶利米哀歌 3:23": ["faithfulness", "hope"],
  "申命记 7:9": ["faithfulness", "love"],
  "马太福音 11:29": ["gentleness", "peace", "self_control"],
  "提多书 3:2": ["gentleness", "peace"],
  "箴言 15:1": ["gentleness", "self_control"],
  "彼得后书 1:5-6": ["self_control", "faith", "patience"],
  "提多书 2:11-12": ["self_control", "goodness", "salvation"],
  "哥林多前书 9:25": ["self_control", "strength"],
  "箴言 16:32": ["self_control", "patience", "strength"],
  // 扩充金句（导航站读经常用 + RCL 节期核心）
  "诗篇 1:1-2": ["wisdom", "faithfulness", "self_control"],
  "诗篇 19:14": ["wisdom", "presence", "self_control"],
  "诗篇 51:10": ["salvation", "presence", "goodness"],
  "诗篇 103:1-2": ["gratitude", "love", "joy"],
  "诗篇 121:1-2": ["presence", "strength", "hope"],
  "箴言 9:10": ["wisdom", "faith"],
  "箴言 18:10": ["strength", "presence", "peace"],
  "以赛亚书 9:6": ["hope", "peace", "salvation"],
  "以赛亚书 53:5": ["salvation", "peace", "love"],
  "以赛亚书 55:6": ["presence", "salvation", "faith"],
  "哈巴谷书 3:17-18": ["joy", "faith", "hope"],
  "西番雅书 3:17": ["joy", "love", "presence"],
  "马太福音 5:3": ["hope", "gentleness", "peace"],
  "马太福音 6:9-10": ["presence", "faith", "wisdom"],
  "马太福音 7:7": ["faith", "hope", "presence"],
  "马可福音 10:45": ["love", "salvation", "gentleness"],
  "路加福音 6:31": ["love", "kindness", "goodness"],
  "路加福音 19:10": ["salvation", "love", "hope"],
  "约翰福音 1:12": ["salvation", "faith", "love"],
  "约翰福音 6:35": ["presence", "salvation", "faith"],
  "约翰福音 10:10": ["hope", "salvation", "joy"],
  "约翰福音 11:25-26": ["hope", "faith", "salvation"],
  "约翰福音 14:6": ["faith", "salvation", "wisdom"],
  "使徒行传 1:8": ["strength", "presence", "faithfulness"],
  "使徒行传 16:31": ["salvation", "faith"],
  "罗马书 1:16": ["salvation", "faith", "strength"],
  "罗马书 3:23-24": ["salvation", "love", "faith"],
  "罗马书 5:8": ["love", "salvation"],
  "罗马书 6:23": ["salvation", "hope"],
  "罗马书 8:1": ["salvation", "peace", "hope"],
  "罗马书 8:38-39": ["love", "hope", "peace"],
  "罗马书 10:9": ["salvation", "faith"],
  "哥林多前书 10:13": ["faithfulness", "strength", "patience"],
  "哥林多前书 13:4-5": ["love", "patience", "kindness", "gentleness"],
  "哥林多前书 15:58": ["strength", "faithfulness", "hope"],
  "哥林多后书 5:17": ["salvation", "hope", "joy"],
  "加拉太书 2:20": ["faith", "love", "presence"],
  "以弗所书 2:10": ["goodness", "faithfulness", "love"],
  "以弗所书 3:20-21": ["hope", "faith", "gratitude"],
  "以弗所书 6:10": ["strength", "faith"],
  "腓立比书 1:6": ["hope", "faithfulness", "faith"],
  "腓立比书 2:3": ["gentleness", "love", "self_control"],
  "腓立比书 4:8": ["wisdom", "goodness", "self_control"],
  "腓立比书 4:19": ["presence", "gratitude", "hope"],
  "歌罗西书 3:23": ["faithfulness", "goodness"],
  "帖撒罗尼迦前书 5:16-18": ["joy", "gratitude", "peace"],
  "提摩太前书 4:12": ["faithfulness", "love", "self_control"],
  "提摩太后书 3:16-17": ["wisdom", "goodness", "faithfulness"],
  "希伯来书 4:16": ["presence", "comfort", "hope"],
  "希伯来书 12:1-2": ["faith", "patience", "hope"],
  "希伯来书 13:5": ["presence", "peace", "faithfulness"],
  "雅各书 1:5": ["wisdom", "faith"],
  "雅各书 4:8": ["presence", "self_control", "faith"],
  "彼得前书 2:9": ["presence", "love", "goodness"],
  "彼得前书 3:15": ["hope", "gentleness", "faith"],
  "约翰一书 1:9": ["salvation", "faithfulness", "peace"],
  "约翰一书 4:7-8": ["love"],
  "犹大书 1:24-25": ["salvation", "joy", "hope"],
  "启示录 3:20": ["presence", "salvation", "love"],
  "启示录 22:13": ["presence", "hope", "faithfulness"],
  // 第二批扩充（改革宗导航/读经常用 · CUV）
  "创世记 15:6": ["faith", "salvation"],
  "出埃及记 34:6": ["love", "kindness", "faithfulness"],
  "民数记 6:24-26": ["peace", "presence", "love"],
  "申命记 6:4-5": ["love", "faith", "wisdom"],
  "撒母耳记上 16:7": ["wisdom", "presence"],
  "历代志上 16:34": ["gratitude", "love", "goodness"],
  "诗篇 8:1": ["gratitude", "presence"],
  "诗篇 32:1": ["salvation", "peace", "joy"],
  "诗篇 42:1": ["presence", "hope"],
  "诗篇 51:17": ["gentleness", "salvation"],
  "诗篇 73:26": ["presence", "strength", "hope"],
  "诗篇 90:12": ["wisdom", "self_control"],
  "诗篇 118:24": ["joy", "gratitude"],
  "诗篇 133:1": ["love", "peace", "kindness"],
  "传道书 12:13": ["wisdom", "faith"],
  "以赛亚书 6:8": ["faithfulness", "strength"],
  "以赛亚书 40:8": ["faithfulness", "wisdom"],
  "以赛亚书 53:6": ["salvation", "love"],
  "以西结书 36:26": ["salvation", "presence", "hope"],
  "约珥书 2:28": ["presence", "hope"],
  "哈巴谷书 2:4": ["faith", "salvation"],
  "玛拉基书 3:6": ["faithfulness", "presence"],
  "马太福音 5:9": ["peace", "love"],
  "马太福音 9:13": ["kindness", "salvation", "love"],
  "马太福音 16:24": ["faith", "strength"],
  "马太福音 22:37-39": ["love", "faith"],
  "马可福音 8:36": ["wisdom", "salvation"],
  "路加福音 9:23": ["faith", "strength"],
  "路加福音 11:9": ["faith", "hope", "presence"],
  "约翰福音 3:3": ["salvation", "hope"],
  "约翰福音 5:24": ["salvation", "faith", "hope"],
  "约翰福音 13:34-35": ["love", "kindness"],
  "约翰福音 16:33": ["peace", "strength", "hope"],
  "约翰福音 17:3": ["salvation", "presence", "wisdom"],
  "使徒行传 4:12": ["salvation", "faith"],
  "罗马书 5:1": ["peace", "faith", "salvation"],
  "罗马书 8:31": ["strength", "hope", "presence"],
  "罗马书 11:36": ["gratitude", "presence", "wisdom"],
  "哥林多前书 1:18": ["salvation", "wisdom", "strength"],
  "哥林多前书 15:3-4": ["salvation", "hope", "faith"],
  "哥林多后书 4:16-18": ["hope", "strength", "patience"],
  "加拉太书 6:9": ["patience", "goodness", "hope"],
  "以弗所书 1:3": ["gratitude", "love", "presence"],
  "以弗所书 2:4-5": ["love", "salvation"],
  "腓立比书 2:5-7": ["gentleness", "love", "faith"],
  "腓立比书 3:8": ["faith", "love", "wisdom"],
  "歌罗西书 1:15-16": ["presence", "wisdom", "faith"],
  "提摩太前书 2:5": ["salvation", "faith"],
  "提摩太后书 2:15": ["wisdom", "faithfulness"],
  "提多书 3:5": ["salvation", "love"],
  "希伯来书 1:3": ["presence", "salvation", "wisdom"],
  "希伯来书 10:23": ["hope", "faithfulness"],
  "希伯来书 11:6": ["faith", "presence"],
  "雅各书 1:22": ["faithfulness", "goodness"],
  "彼得前书 1:3": ["hope", "salvation", "joy"],
  "彼得前书 2:24": ["salvation", "love"],
  "彼得后书 3:9": ["patience", "love", "hope"],
  "约翰一书 4:10": ["love", "salvation"],
  "约翰一书 5:11-12": ["salvation", "hope", "faith"],
  "启示录 1:8": ["presence", "hope", "faithfulness"],
  "启示录 21:5": ["hope", "joy", "presence"],
  "启示录 22:20": ["hope", "joy", "faith"],
  // 第三批：圣经金句500句导入
  "创世记 1:3": ["presence", "wisdom", "hope"],
  "创世记 1:27": ["love", "presence", "gratitude"],
  "创世记 50:20": ["hope", "goodness", "faith"],
  "出埃及记 3:14": ["presence", "faithfulness"],
  "约书亚记 1:8": ["wisdom", "faithfulness", "strength"],
  "约书亚记 24:15": ["faithfulness", "faith"],
  "路得记 1:16": ["faithfulness", "love", "presence"],
  "约伯记 19:25": ["hope", "salvation", "faith"],
  "约伯记 23:10": ["patience", "faith", "hope"],
  "诗篇 23:4": ["comfort", "presence", "peace"],
  "诗篇 30:5": ["hope", "joy", "comfort"],
  "诗篇 34:18": ["comfort", "presence", "gentleness"],
  "诗篇 91:1": ["presence", "strength", "peace"],
  "诗篇 119:11": ["wisdom", "self_control", "faithfulness"],
  "箴言 4:23": ["wisdom", "self_control", "goodness"],
  "箴言 22:6": ["wisdom", "faithfulness", "love"],
  "以赛亚书 40:11": ["comfort", "gentleness", "love"],
  "以赛亚书 55:8": ["wisdom", "faith"],
  "耶利米书 31:3": ["love", "faithfulness", "hope"],
  "弥迦书 5:2": ["hope", "salvation", "presence"],
  "撒迦利亚书 4:6": ["strength", "faith", "presence"],
  "马太福音 5:4": ["comfort", "hope"],
  "马太福音 5:8": ["presence", "peace", "goodness"],
  "马太福音 7:12": ["love", "kindness", "goodness"],
  "马太福音 18:20": ["presence", "love"],
  "马太福音 24:35": ["faithfulness", "hope"],
  "约翰福音 1:1": ["presence", "wisdom", "salvation"],
  "约翰福音 1:14": ["presence", "love", "salvation"],
  "约翰福音 1:29": ["salvation", "love"],
  "约翰福音 4:24": ["presence", "faith", "wisdom"],
  "约翰福音 8:32": ["wisdom", "salvation", "hope"],
  "约翰福音 10:11": ["love", "salvation", "presence"],
  "使徒行传 2:38": ["salvation", "presence"],
  "罗马书 8:37": ["strength", "love", "hope"],
  "罗马书 12:1": ["faithfulness", "love", "self_control"],
  "哥林多后书 5:21": ["salvation", "love"],
  "以弗所书 6:11": ["strength", "faith"],
  "腓立比书 1:21": ["presence", "hope", "faith"],
  "腓立比书 4:4": ["joy", "hope"],
  "希伯来书 4:12": ["wisdom", "presence"],
  "希伯来书 13:8": ["faithfulness", "presence", "hope"],
  "雅各书 1:19": ["self_control", "gentleness", "wisdom"],
  "雅各书 4:7": ["strength", "self_control", "faith"],
  "彼得前书 4:8": ["love", "kindness"],
  "约翰一书 4:8": ["love"],
  "约翰一书 4:18": ["love", "peace", "faith"],
  // 第四批：圣经应许（Clarke PBP CUV · 精选）
  "诗篇 84:11": ["gratitude", "goodness", "presence"],
  "诗篇 34:9": ["presence", "faith", "gratitude"],
  "诗篇 34:10": ["presence", "hope", "gratitude"],
  "诗篇 103:3": ["salvation", "comfort", "love"],
  "诗篇 4:8": ["peace", "presence"],
  "诗篇 91:4": ["presence", "strength", "faithfulness"],
  "诗篇 121:8": ["presence", "strength"],
  "诗篇 119:165": ["peace", "wisdom", "love"],
  "诗篇 29:11": ["strength", "peace"],
  "以赛亚书 32:18": ["peace", "presence"],
  "诗篇 37:23": ["presence", "wisdom", "faithfulness"],
  "诗篇 48:14": ["presence", "wisdom"],
  "以赛亚书 42:16": ["presence", "wisdom", "hope"],
  "诗篇 91:14": ["love", "salvation", "presence"],
  "诗篇 91:15": ["presence", "salvation", "strength"],
  "箴言 10:22": ["gratitude", "peace", "goodness"],
  "诗篇 55:22": ["comfort", "peace", "faith"],
  "诗篇 46:1": ["strength", "presence", "comfort"],
  "诗篇 34:19": ["comfort", "salvation", "hope"],
  "以赛亚书 46:4": ["presence", "comfort", "salvation"],
  "以赛亚书 43:2": ["presence", "strength", "peace"],
  "诗篇 138:7": ["salvation", "strength", "hope"],
  "诗篇 145:14": ["comfort", "strength", "kindness"],
  "弥迦书 7:8": ["hope", "presence", "strength"],
  "耶利米哀歌 3:31": ["hope", "faithfulness", "comfort"],
  "耶利米哀歌 3:32": ["kindness", "comfort", "love"],
  "哥林多后书 1:5": ["comfort", "love"],
  "哥林多后书 4:8-9": ["hope", "strength", "patience"],
  "以赛亚书 43:25": ["salvation", "love", "faithfulness"],
  "诗篇 103:12": ["salvation", "love", "peace"],
  "弥迦书 7:18": ["salvation", "kindness", "love"],
  "弥迦书 7:19": ["salvation", "kindness", "hope"],
  "以赛亚书 44:22": ["salvation", "love", "hope"],
  "何西阿书 14:4": ["love", "salvation", "kindness"],
  "约翰一书 1:7": ["salvation", "presence", "faithfulness"],
  "约翰一书 2:1": ["salvation", "presence", "love"],
  "罗马书 5:10": ["salvation", "peace", "love"],
  "罗马书 8:15": ["love", "presence", "faith"],
  "约翰一书 3:1": ["love", "presence", "gratitude"],
  "以弗所书 2:19": ["presence", "love", "hope"],
  "诗篇 50:15": ["salvation", "presence", "gratitude"],
  "以赛亚书 65:24": ["presence", "faithfulness", "hope"],
  "耶利米书 29:12": ["presence", "faith", "hope"],
  "约翰福音 15:7": ["presence", "faith", "hope"],
  "约翰福音 14:13": ["faith", "presence", "hope"],
  "约翰一书 5:14": ["faith", "presence", "peace"],
  "腓立比书 2:13": ["presence", "faithfulness", "goodness"],
  "约翰福音 10:28": ["salvation", "hope", "presence"],
  "约翰福音 10:29": ["salvation", "presence", "strength"],
  "以赛亚书 40:29": ["strength", "comfort"],
  "以赛亚书 12:2": ["salvation", "strength", "faith"],
  "约翰一书 4:4": ["strength", "presence", "faith"],
  "约翰一书 5:4": ["faith", "strength", "hope"],
  "希伯来书 7:25": ["salvation", "presence", "hope"],
  "约翰福音 14:18": ["presence", "comfort", "love"],
  "约翰福音 6:37": ["presence", "salvation", "hope"],
  "创世记 15:1": ["strength", "presence", "hope"],
  "出埃及记 33:14": ["presence", "peace"],
  "申命记 31:8": ["presence", "strength", "peace"],
  "申命记 33:27": ["presence", "strength"],
  "以赛亚书 41:13": ["strength", "presence", "comfort"],
  "以赛亚书 49:16": ["love", "presence", "faithfulness"],
  "耶利米哀歌 3:24": ["hope", "presence", "faith"],
  "诗篇 138:8": ["faithfulness", "love", "hope"],
  "诗篇 31:24": ["strength", "hope", "faith"],
  "诗篇 147:3": ["comfort", "kindness"],
  "诗篇 34:7": ["presence", "salvation", "strength"],
  "诗篇 91:11": ["presence", "strength"],
  "诗篇 32:8": ["wisdom", "presence"],
  "诗篇 103:13": ["kindness", "love"],
  "以赛亚书 30:18": ["kindness", "hope", "patience"],
  "以赛亚书 30:21": ["wisdom", "presence"],
  "以赛亚书 32:17": ["peace", "goodness"],
  "以赛亚书 54:7": ["love", "hope", "comfort"],
  "以赛亚书 54:8": ["love", "kindness", "salvation"],
  "以赛亚书 58:11": ["presence", "gratitude", "strength"],
  "约翰福音 14:23": ["love", "presence"],
  "约翰福音 15:9": ["love", "presence"],
  "约翰福音 1:16": ["gratitude", "love", "salvation"],
  "罗马书 5:5": ["hope", "love", "presence"],
  "罗马书 8:26": ["presence", "comfort", "faith"],
  "罗马书 3:24": ["salvation", "love"],
  "罗马书 6:14": ["salvation", "strength"],
  "哥林多前书 1:30": ["wisdom", "salvation", "presence"],
  "哥林多前书 1:8": ["faithfulness", "hope", "strength"],
  "加拉太书 3:26": ["faith", "love", "presence"],
  "彼得后书 1:4": ["hope", "presence", "salvation"],
  "彼得前书 1:5": ["faith", "salvation", "hope"],
  "帖撒罗尼迦后书 3:3": ["faithfulness", "strength", "peace"],
  "帖撒罗尼迦前书 5:24": ["faithfulness", "hope"],
  "希伯来书 2:18": ["comfort", "strength", "salvation"],
  "希伯来书 8:12": ["salvation", "love", "faithfulness"],
  "希伯来书 12:6": ["love", "wisdom"],
  "希伯来书 13:6": ["strength", "peace", "faith"],
  "雅各书 1:12": ["hope", "patience", "love"],
  "启示录 21:3": ["presence", "hope", "love"],
  "以西结书 36:27": ["presence", "faithfulness", "goodness"],
  "路加福音 11:13": ["presence", "goodness", "faith"],
  "约翰福音 16:13": ["wisdom", "presence"],
  "罗马书 8:16": ["presence", "love", "faith"],
  "约翰一书 4:16": ["love", "presence", "faith"],
  "马太福音 21:22": ["faith", "hope"],
  "诗篇 9:10": ["faith", "presence", "hope"],
  "诗篇 94:14": ["faithfulness", "presence"],
  "诗篇 37:28": ["faithfulness", "presence", "goodness"],
  "诗篇 16:5": ["presence", "gratitude"],
  "诗篇 36:9": ["presence", "wisdom"],
  "诗篇 27:14": ["hope", "strength", "patience"],
  "诗篇 32:7": ["presence", "salvation", "joy"],
  "约伯记 5:19": ["salvation", "strength", "hope"],
  "箴言 24:16": ["hope", "strength", "patience"],
  "箴言 4:18": ["wisdom", "hope", "goodness"],
  "箴言 2:6": ["wisdom", "presence"],
  "箴言 3:24": ["peace", "presence"],
  "以赛亚书 12:3": ["salvation", "joy"],
  "以赛亚书 35:4": ["strength", "salvation", "hope"],
  "以赛亚书 43:4": ["love", "presence"],
  "以赛亚书 49:13": ["comfort", "joy", "kindness"],
  "以赛亚书 55:3": ["faithfulness", "hope", "presence"],
  "耶利米书 31:33": ["presence", "faithfulness", "love"],
  "利未记 26:12": ["presence", "love"],
  "歌罗西书 3:3": ["presence", "hope"],
  "歌罗西书 3:4": ["hope", "presence", "joy"],
  "以弗所书 3:12": ["faith", "presence", "peace"],
  "腓立比书 4:7": ["peace", "presence"],
  "帖撒罗尼迦后书 3:16": ["peace", "presence"],
  "提多书 2:14": ["salvation", "goodness", "love"],
  "约翰福音 17:17": ["wisdom", "presence", "salvation"],
  "约翰福音 7:38": ["presence", "hope", "salvation"],
  "罗马书 14:17": ["peace", "joy", "goodness"],
  "罗马书 5:3-4": ["hope", "patience", "joy"],
  "彼得前书 1:7": ["faith", "hope", "joy"],
  "希伯来书 10:14": ["salvation", "faithfulness"],
  "希伯来书 12:11": ["peace", "patience", "goodness"],
  "撒迦利亚书 13:1": ["salvation", "hope"],
  "玛拉基书 4:2": ["hope", "salvation", "joy"],
  "诗篇 85:8": ["peace", "presence"],
  "诗篇 112:7": ["faith", "peace", "strength"],
  "诗篇 125:2": ["presence", "faithfulness"],
  "诗篇 145:19": ["salvation", "presence", "hope"],
  "以赛亚书 26:12": ["peace", "presence"],
  "以赛亚书 41:17": ["presence", "comfort", "hope"],
  "何西阿书 6:1": ["salvation", "comfort", "hope"],
  "雅各书 4:6": ["gratitude", "gentleness"],
  "约翰一书 3:2": ["hope", "love", "presence"],
  "哥林多后书 3:18": ["presence", "hope", "joy"],
  "哥林多后书 6:18": ["love", "presence"],
  "以弗所书 1:13": ["salvation", "faith", "presence"],
  "诗篇 107:9": ["gratitude", "comfort"],
  "诗篇 126:6": ["hope", "joy", "patience"],
  "出埃及记 15:26": ["salvation", "presence", "faithfulness"],
  "申命记 4:31": ["kindness", "faithfulness", "presence"],
  "约翰福音 14:21": ["love", "presence"],
  "约翰福音 16:24": ["joy", "faith", "hope"],
  "约翰福音 13:1": ["love", "faithfulness"],
  "彼得后书 1:3": ["presence", "wisdom"],
  "帖撒罗尼迦前书 5:23": ["peace", "presence", "salvation"],
  "以赛亚书 61:3": ["comfort", "joy", "hope"],
  "以赛亚书 12:1": ["gratitude", "comfort"],
  "罗马书 8:33": ["salvation", "peace"],
  "加拉太书 5:16": ["self_control", "presence"],
  "希伯来书 4:14": ["faith", "presence"],
  "希伯来书 1:14": ["presence", "salvation"],
  "诗篇 119:71": ["wisdom", "patience"],
  "箴言 3:12": ["love", "wisdom"],
  "以赛亚书 33:16": ["presence", "strength"],
  "以赛亚书 54:17": ["strength", "peace", "salvation"],
  "诗篇 103:17": ["love", "faithfulness"],
  "诗篇 34:15": ["presence", "salvation"],
  "马太福音 7:11": ["goodness", "faith", "love"],
  "马太福音 26:28": ["salvation", "love"],
  "约翰福音 1:17": ["salvation", "love", "faithfulness"],
  "加拉太书 3:13": ["salvation", "love"],
  "以弗所书 2:18": ["presence", "peace"],
  "耶利米书 3:22": ["salvation", "hope", "love"],
  "耶利米书 32:40": ["faithfulness", "presence", "love"],
  "以赛亚书 44:3": ["presence", "hope", "gratitude"],
  "以赛亚书 63:9": ["presence", "love", "salvation"],
  "以西结书 36:25": ["salvation", "presence"],
  "彼得后书 2:9": ["salvation", "faithfulness"],
  "哥林多后书 1:22": ["presence", "faithfulness"],
  "提摩太后书 1:9": ["salvation", "love", "faithfulness"],
  "诗篇 130:4": ["salvation", "faith"],
  "诗篇 84:7": ["strength", "presence"],
  "诗篇 92:12": ["strength", "goodness"],
  "约翰一书 5:18": ["presence", "salvation", "strength"],
  "约翰福音 14:19": ["presence", "hope", "salvation"],
  "约翰福音 16:27": ["love", "faith"],
  "诗篇 27:10": ["presence", "comfort"],
  "诗篇 41:1": ["kindness", "salvation"],
  "诗篇 9:18": ["hope", "comfort"],
  "诗篇 68:5": ["presence", "kindness", "comfort"],
  "诗篇 46:11": ["presence", "strength"],
  "诗篇 66:9": ["presence", "hope"],
  "诗篇 91:7": ["presence", "strength", "peace"],
  "诗篇 91:16": ["salvation", "hope"],
  "箴言 3:2": ["peace", "wisdom", "hope"],
  "箴言 3:6": ["wisdom", "faith", "presence"],
  "箴言 1:33": ["peace", "presence"],
  "箴言 14:26": ["faith", "presence", "strength"],
  "利未记 26:6": ["peace", "presence"],
  "希伯来书 8:10": ["presence", "faithfulness", "love"],
  "耶利米书 30:22": ["presence", "love"],
  "哥林多后书 6:16": ["presence", "love"],
  "以赛亚书 57:18": ["comfort", "hope", "kindness"],
  "以赛亚书 58:9": ["presence", "faith"],
  "诗篇 4:3": ["presence", "faith"],
  "约翰福音 14:14": ["faith", "hope"],
  "约翰一书 5:5": ["faith", "strength"],
  "罗马书 6:11": ["salvation", "presence"],
  "哥林多后书 3:5": ["presence", "strength"],
  "加拉太书 4:7": ["love", "presence", "hope"],
  "启示录 3:19": ["love", "wisdom"],
  "撒迦利亚书 2:5": ["presence", "strength"],
  "诗篇 103:5": ["gratitude", "strength", "joy"],
  "诗篇 103:4": ["salvation", "love", "kindness"],
  "诗篇 42:8": ["love", "presence", "joy"],
  "诗篇 68:20": ["salvation", "presence"],
  "约伯记 22:28": ["hope", "presence"],
  "约伯记 22:27": ["presence", "faith"],
  "诗篇 65:2": ["presence", "faith"],
  "诗篇 34:17": ["salvation", "presence"],
  "诗篇 147:14": ["peace", "gratitude"],
  "希伯来书 10:17": ["salvation", "faithfulness"],
  "约翰一书 3:5": ["salvation", "presence"],
  "何西阿书 14:5": ["hope", "presence"],
  "哥林多后书 1:21": ["presence", "faithfulness"],
  "申命记 30:6": ["love", "presence"],
  "申命记 33:12": ["presence", "peace", "love"],
  "以赛亚书 48:17": ["wisdom", "presence"],
  "以赛亚书 57:19": ["peace", "comfort"],
  "以赛亚书 54:13": ["peace", "wisdom", "love"],
  "以赛亚书 54:5": ["love", "salvation", "presence"],
  "以赛亚书 41:14": ["strength", "salvation", "comfort"],
  "以赛亚书 49:10": ["presence", "comfort", "kindness"],
  "以赛亚书 41:18": ["presence", "hope"],
  "以赛亚书 35:8": ["wisdom", "salvation", "presence"],
  "以赛亚书 32:15": ["presence", "hope"],
  "约翰福音 14:17": ["presence", "wisdom"],
  "约翰福音 15:2": ["presence", "goodness"],
  "罗马书 6:6": ["salvation", "strength"],
  "罗马书 8:27": ["presence", "faith"],
  "罗马书 8:30": ["salvation", "hope"],
  "罗马书 5:9": ["salvation", "peace"],
  "罗马书 16:20": ["peace", "strength", "salvation"],
  "加拉太书 4:6": ["love", "presence"],
  "以弗所书 1:5": ["love", "presence"],
  "以弗所书 1:14": ["hope", "presence", "salvation"],
  "以弗所书 4:30": ["presence", "self_control"],
  "希伯来书 9:14": ["salvation", "presence"],
  "希伯来书 10:19-20": ["presence", "salvation", "hope"],
  "彼得前书 4:14": ["joy", "presence", "strength"],
  "彼得前书 1:19": ["salvation", "love"],
  "彼得后书 1:10": ["faithfulness", "hope"],
  "约翰一书 3:22": ["faith", "presence"],
  "约翰一书 5:20": ["wisdom", "presence", "salvation"],
  "约翰一书 2:27": ["wisdom", "presence"],
  "雅各书 5:15": ["faith", "salvation", "comfort"],
  "哥林多前书 2:12": ["wisdom", "presence"],
  "哥林多前书 2:10": ["wisdom", "presence"],
  "哥林多前书 6:11": ["salvation", "presence"],
  "哥林多后书 5:5": ["presence", "hope"],
  "哥林多后书 4:6": ["presence", "wisdom"],
  "歌罗西书 1:12": ["gratitude", "hope"],
  "帖撒罗尼迦后书 2:13": ["salvation", "presence", "love"],
  "帖撒罗尼迦后书 2:16": ["love", "comfort", "hope"],
  "启示录 1:6": ["presence", "gratitude"],
  "路加福音 1:79": ["peace", "hope"],
  "马太福音 10:30": ["presence", "comfort"],
  "何西阿书 6:3": ["presence", "wisdom", "hope"],
  "耶利米书 6:16": ["peace", "wisdom"],
  "耶利米书 24:7": ["presence", "love", "faith"],
  "耶利米书 16:19": ["strength", "presence", "comfort"],
  "耶利米书 33:8": ["salvation", "faithfulness"],
  "耶利米书 49:11": ["presence", "comfort", "kindness"],
  "以赛亚书 25:4": ["strength", "comfort", "presence"],
  "以赛亚书 51:7": ["strength", "peace", "faith"],
  "以赛亚书 53:11": ["salvation", "love"],
  "以赛亚书 45:25": ["salvation", "joy"],
  "以赛亚书 48:10": ["patience", "presence"],
  "以赛亚书 61:1": ["comfort", "salvation", "hope"],
  "以赛亚书 62:4": ["love", "joy", "presence"],
  "诗篇 25:8": ["goodness", "wisdom"],
  "诗篇 25:12": ["wisdom", "presence"],
  "诗篇 32:2": ["salvation", "peace", "joy"],
  "诗篇 33:18-19": ["presence", "salvation", "hope"],
  "诗篇 31:20": ["presence", "peace"],
  "诗篇 37:25": ["faithfulness", "presence"],
  "诗篇 37:39": ["salvation", "presence", "strength"],
  "诗篇 40:17": ["comfort", "strength"],
  "诗篇 41:3": ["comfort", "presence"],
  "诗篇 65:4": ["presence", "gratitude", "joy"],
  "诗篇 72:12": ["salvation", "kindness", "comfort"],
  "诗篇 89:15": ["joy", "presence"],
  "诗篇 91:12": ["presence", "strength"],
  "诗篇 94:18": ["love", "strength", "comfort"],
  "诗篇 112:2": ["hope", "goodness"],
  "诗篇 112:6": ["faithfulness", "presence"],
  "诗篇 116:15": ["presence", "love"],
  "诗篇 119:67": ["wisdom", "patience"],
  "诗篇 128:2": ["gratitude", "peace"],
  "箴言 1:23": ["presence", "wisdom"],
  "箴言 2:5": ["wisdom", "faith"],
  "箴言 3:33": ["goodness", "presence"],
  "箴言 16:7": ["peace", "goodness"],
  "箴言 16:31": ["wisdom", "goodness"],
  "箴言 22:4": ["wisdom", "gentleness"],
  "约翰福音 17:23": ["love", "presence"],
};

const KEYWORD_TOPICS: Array<{ re: RegExp; topics: SpiritualTopic[] }> = [
  { re: /平安|安息|安静|不要忧愁|不要胆怯/, topics: ["peace", "comfort"] },
  { re: /喜乐|欢喜|快乐|欢呼/, topics: ["joy"] },
  { re: /盼望|指望|等候/, topics: ["hope", "patience"] },
  { re: /信实|诚实|不落空|不改变/, topics: ["faithfulness"] },
  { re: /信|倚靠|仰赖/, topics: ["faith"] },
  { re: /仁爱|慈爱|爱你|爱我们|神爱/, topics: ["love"] },
  { re: /怜悯|恩慈|恩待/, topics: ["kindness", "love"] },
  { re: /良善|美善|善/, topics: ["goodness"] },
  { re: /温柔|柔和|谦卑/, topics: ["gentleness"] },
  { re: /忍耐|恒久|耐心|不急躁/, topics: ["patience"] },
  { re: /节制|谨守|自制|醒着|警醒/, topics: ["self_control"] },
  { re: /力量|刚强|坚固|帮助/, topics: ["strength"] },
  { re: /智慧|聪明|旨意|教训/, topics: ["wisdom"] },
  { re: /感谢|称谢|恩典|赏赐/, topics: ["gratitude"] },
  { re: /同在|与你同在|牧者|避难所/, topics: ["presence"] },
  { re: /救|永生|得救|赎/, topics: ["salvation"] },
  { re: /安慰|擦去|顾念|卸给/, topics: ["comfort"] },
];

export function resolveTopics(
  verse: Pick<Verse, "reference" | "text">,
): SpiritualTopic[] {
  const fromMap = TOPIC_BY_REFERENCE[verse.reference];
  const set = new Set<SpiritualTopic>(fromMap ?? []);

  for (const rule of KEYWORD_TOPICS) {
    if (rule.re.test(verse.text)) {
      for (const t of rule.topics) set.add(t);
    }
  }

  if (set.size === 0) {
    set.add("presence");
  }

  return [...set];
}

export function withTopics(verse: Verse): Verse {
  return { ...verse, topics: resolveTopics(verse) };
}

export function listVersesByTopic(topic: SpiritualTopic | "all"): Verse[] {
  const pool = getLocalCuvPool().map(withTopics).map(attachEnglish);
  if (topic === "all") return pool;
  return pool.filter((v) => v.topics?.includes(topic));
}

export function isFruitTopic(topic: SpiritualTopic): boolean {
  return (FRUIT_TOPICS as string[]).includes(topic);
}

/** 按日期轮换「今日果子」— 九果循环，无需 API */
export function getFruitOfDay(date?: string): {
  fruit: SpiritualTopic;
  label: string;
  index: number;
} {
  const key = date ?? getTodayKey();
  const index = hashDateSeed(key, "fruit-of-day") % FRUIT_TOPICS.length;
  const fruit = FRUIT_TOPICS[index] ?? "love";
  return { fruit, label: TOPIC_LABELS[fruit], index };
}

export function countByTopic(topic: SpiritualTopic): number {
  return listVersesByTopic(topic).length;
}
